spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  catalogue-service:
    base-uri: ${CUSTOMER_SERVICE_URI:localhost:8085}
    customers-uri: ${app.catalogue-service.base-uri}/customers