version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mongo-orders:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: dbuser
      MONGODB_PASSWORD: dbpassword
      MONGODB_DATABASE: orders
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile.dev
    links:
      - kafka
      - mongo-orders
    environment:
      MONGO_HOST: mongo-orders
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  mongo-warehouse:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: dbuser
      MONGODB_PASSWORD: dbpassword
      MONGODB_DATABASE: warehouse
  warehouse-service:
    build:
      context: ./warehouse-service
      dockerfile: Dockerfile.dev
    links:
      - kafka
      - mongo-warehouse
    environment:
      MONGO_HOST: mongo-warehouse
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  mongo-finance:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: dbuser
      MONGODB_PASSWORD: dbpassword
      MONGODB_DATABASE: warehouse
  warehouse-finance:
    build:
      context: ./finance-service
      dockerfile: Dockerfile.dev
    links:
      - kafka
      - mongo-finance
    environment:
      MONGO_HOST: mongo-finance
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  mongo-catalogue:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: dbuser
      MONGODB_PASSWORD: dbpassword
      MONGODB_DATABASE: catalogue
  catalogue-service:
    build:
      context: ./catalogue-service
      dockerfile: Dockerfile.dev
      args:
        - port=8082
    links:
      - mongo-catalogue
    environment:
      MONGO_HOST: mongo-catalogue
