version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  mongo:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: dbuser
      MONGODB_PASSWORD: dbpassword
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile.dev
    links:
      - kafka
      - mongo
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  warehouse-service:
    build:
      context: ./warehouse-service
      dockerfile: Dockerfile.dev
    links:
      - kafka
      - mongo
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092